name: Deploy to GCE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCE_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: SSH and Update Code
        run: |
          gcloud compute ssh server-fl \
            --zone us-central1-c \
            --command "cd /home/ngodinh2339/NCKH/server-flower && git fetch origin main && git reset --hard origin/main && git pull origin main"
